/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
  /* someSidebar: {
    Backend: [
      'dev-ops/devops',
      'backend/java',
      'backend/nodejs',
      'backend/python',
    ],
    Databases: [
      'databases/nosql/cassandra',
      'databases/nosql/mongodb',
      'databases/sql',
      'databases/sql/mariadb',
      'databases/sql/mysql',
      'databases/sql/postgres',
    ],
    DevOps: [
      'devops/cicd',
      'devops/gitops',
    ],
    DevSecOps: [
      'devsecops/tools',
      'devsecops/use-cases',
    ],
    Frontend: [
      'frontend/angular',
      'frontend/nextjs',
      'frontend/react',
    ],
    'No Code/Low Code': [
      'no-code-low-code/appsmith',
      'no-code-low-code/other',
    ],
    Streaming: [
      'streaming/kafka',
    ],
    'Other Category': [
      'explore-services/service-list',
    ],
  },*/
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
